name: v2ray_app
description: "A Modern Cyberpunk Xray v26 VPN Client Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # پکیج قدرتمند Xray v26 با پشتیبانی کامل از XHTTP, REALITY, gRPC, Hysteria2
  flutter_v2ray_client: ^3.5.0

  # دریافت سرورها از فایربیس
  http: ^1.2.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
