name: xray_ultra
description: "A new Flutter Xray client application with Firebase Realtime sync."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # آیکون‌های استاندارد متریال
  cupertino_icons: ^1.0.8

  # آخرین نسخه پلاگین v2ray جهت پشتیبانی از ترانسپورت‌های جدید (xhttp و غیره)
  flutter_v2ray_client: ^0.2.2

  # ارتباط با فایربیس و دریافت کانفیگ‌ها و به‌روزرسانی حجم
  http: ^1.2.0

  # ذخیره‌سازی نشست کاربر و آیدی در حافظه محلی
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # در صورت وجود تصویر یا لوگو برای نوتیفیکیشن یا برنامه‌ها می‌توانید مسیر زیر را فعال کنید:
  # assets:
  #   - assets/
